# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b7a7f5211331772cf774b5de9e86ffc9a1f8e5c0a2623a54acd68d07402a13789487795069c3d406e3e03bbbd752daedbb872ba20f7e86b5952aa9d72a13fe58

test:
  secret_key_base: 45d35d0e5e4268111d18269fdc21fb0f4304c1dcf35cbc1c0ad9ede800739d95424984ef167e0db1febec26e636b909f549628d10ac1abb526af54b4307c6d46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
